security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: plaintext  

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER 

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: 'password'
                        roles: ['ROLE_ADMIN']
                    user:
                        password: 'password'
                        roles: ['ROLE_USER']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: in_memory
            http_basic: ~ 

    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }  
